### ISSUE TITLE
Enumerable#minmax に Comparable はいらない(たぶん)

### ISSUE THREAD

**Issue by pocke** [pocke/zatsu#33]
![200522174724](https://user-images.githubusercontent.com/4361134/82649539-537b5900-9c54-11ea-936d-0698daae2376.png)

https://github.com/rurema/doctree/pull/2260#discussion_r429113650

**Comment by pocke** [comment]
# TODO

以下のメソッドのドキュメントが書かれた時のコミット時点のコードを読んで、Comparableが使われていないことを確認する

* [x] Enumerable#minmax  https://github.com/ruby/ruby/commit/3f2fe372005b0bd1f6535ffaaf23ff8ea4f8271f
* [x] Enumerable#min, Enumerable#max ruby/ruby@84f0b051de55b80211eab0ad2438f500af45e4a5
* [x] Array#min, Array#max https://github.com/ruby/ruby/commit/68a6f2e9e0c6fc2ba09463c848dbbb4ece3e07a1

**Comment by pocke** [comment]
コミット時点も、現時点でも、Comparableは必要なさそう

**Comment by pocke** [comment]
PRした https://github.com/ruby/ruby/pull/3131
